### ISSUE TITLE
gpkg: A specific commit hash for GoCSI dependency

### ISSUE THREAD

**Issue by akutz** [codedellemc/csi-nfs#1]
Hi,

I think it makes sense to update the `Gopkg.toml` file with a specific commit hash for GoCSI:

```toml
[[constraint]]
  branch = "master"
  name = "github.com/codedellemc/gocsi"
```

I'd switch `branch` for `version` (which is [recommended](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#constraint) by the Gopkg docs) and point to a specific Git ref or tag. Otherwise this is a sliding dependency that will change every time the lock file is updated from the toml file.
